# Generated by Django 3.2 on 2021-04-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_nytmoviereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.BooleanField()),
                ('jokes', models.BooleanField()),
                ('chuckNorris', models.BooleanField()),
                ('movieReview', models.BooleanField()),
                ('periodicityNumber', models.IntegerField(default=1)),
                ('periodicity', models.CharField(max_length=7)),
            ],
        ),
    ]
