# Generated by Django 3.2 on 2021-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='tweetingTimes',
            field=models.IntegerField(default=1),
        ),
    ]
