# Generated by Django 3.2 on 2021-05-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_random_tweetingtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalisedJoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryAny', models.BooleanField()),
                ('categoryCustom', models.BooleanField()),
                ('categoryProgramming', models.BooleanField()),
                ('categoryMisc', models.BooleanField()),
                ('categoryDark', models.BooleanField()),
                ('categoryPun', models.BooleanField()),
                ('categorySpooky', models.BooleanField()),
                ('categoryChristmas', models.BooleanField()),
                ('flagNsfw', models.BooleanField()),
                ('flagReligious', models.BooleanField()),
                ('flagPolitical', models.BooleanField()),
                ('flagRacist', models.BooleanField()),
                ('flagSexist', models.BooleanField()),
                ('flagExplicit', models.BooleanField()),
                ('typeSingle', models.BooleanField()),
                ('typeDouble', models.BooleanField()),
                ('searchString', models.TextField(default='')),
            ],
        ),
    ]
