# Generated by Django 3.2 on 2021-05-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_personalisedjoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalisedjoke',
            name='typeDouble',
        ),
        migrations.RemoveField(
            model_name='personalisedjoke',
            name='typeSingle',
        ),
    ]
