# Generated by Django 3.2 on 2021-05-02 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0006_auto_20210502_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryAny',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryChristmas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryCustom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryDark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryMisc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryProgramming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categoryPun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='categorySpooky',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='flagExplicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='flagNsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='flagPolitical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='flagRacist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='flagReligious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='flagSexist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalisedjoke',
            name='searchString',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='random',
            name='periodicity',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='seconds', max_length=7),
        ),
        migrations.AlterField(
            model_name='random',
            name='periodicityNumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='random',
            name='tweetingTimes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
