# Generated by Django 3.2 on 2021-05-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0007_auto_20210502_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuckfact',
            name='fact',
        ),
        migrations.AddField(
            model_name='chuckfact',
            name='searchString',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
